"""PIM Services Module

This module contains service classes for external integrations and background operations:

- gdsn_sync: GDSN data pool publication and subscription services
- search_rank_tracker: Digital shelf analytics and search rank monitoring services
- price_parity: Price parity monitoring and competitive price tracking services
- ai_enrichment: AI-powered content enrichment services (OpenAI, Claude)
- ai_translation: AI-powered translation services with glossary support
- ai_categorization: AI-powered automatic product categorization services
- image_variants: Channel-specific image variants generation service
- merge_survive: MDM merge/survive service for product deduplication
- print_catalog: Print catalog generator using Frappe print formats with PDF output
- quality_scorer: Unified quality scoring service wrapping completeness and scoring utilities
"""

from frappe_pim.pim.services.gdsn_sync import (
    GDSNDataPoolClient,
    GDSNSyncService,
    publish_to_data_pool,
    subscribe_to_product,
    get_sync_status,
    process_incoming_cin,
    process_incoming_cip,
    sync_product_to_gdsn,
    sync_all_products_to_gdsn,
)

from frappe_pim.pim.services.search_rank_tracker import (
    SearchRankTrackerService,
    KeywordConfig,
    RankResult,
    RankChange,
    TrackingResult,
    TrendData,
    RankTrackingMethod,
    RankChangeType,
    RankAlertSeverity,
    track_product_rankings,
    get_product_rank_history,
    get_rank_trends,
    compare_channel_rankings,
    get_share_of_search,
    schedule_rank_tracking,
    scheduled_rank_tracking,
)

from frappe_pim.pim.services.price_parity import (
    PriceParityMonitorService,
    PricePoint,
    PriceComparison,
    PriceChange,
    PriceViolation,
    ParityResult,
    PriceTrend,
    CompetitorPrice,
    ParityStatus,
    PriceChangeType,
    AlertSeverity,
    PriceType,
    ViolationType,
    monitor_product_prices,
    get_price_parity_status,
    get_price_history,
    get_price_trends,
    compare_channel_prices,
    get_competitor_analysis,
    check_map_violations,
    get_price_alerts,
    schedule_price_monitoring,
    scheduled_price_monitoring,
)

from frappe_pim.pim.services.ai_enrichment import (
    AIEnrichmentService,
    AIProvider,
    EnrichmentType,
    EnrichmentStatus,
    ConfidenceLevel,
    EnrichmentRequest,
    EnrichmentSuggestion,
    EnrichmentResult,
    BulkEnrichmentResult,
    generate_product_description,
    generate_seo_content,
    generate_bullet_points,
    extract_product_attributes,
    suggest_product_categories,
    enrich_product,
    bulk_enrich_products,
    get_enrichment_status,
    approve_enrichment,
    reject_enrichment,
    get_pending_approvals,
    get_available_enrichment_types,
    get_ai_providers,
)

from frappe_pim.pim.services.ai_translation import (
    AITranslationService,
    TranslationProvider,
    TranslationStatus,
    TranslationQuality,
    ContentType,
    GlossaryMatchType,
    GlossaryTerm,
    Glossary,
    TranslationMemoryEntry,
    TranslationRequest,
    TranslationResult,
    BulkTranslationResult,
    ProductTranslation,
    TranslationMemoryManager,
    GlossaryManager,
    translate_text,
    translate_product,
    bulk_translate_products,
    get_translation_memory_stats,
    lookup_translation,
    list_glossaries,
    get_glossary,
    create_glossary,
    add_glossary_term,
    get_supported_languages,
    get_translation_providers,
    approve_translation,
    reject_translation,
    get_pending_translations,
    test_translation_connection,
)

from frappe_pim.pim.services.ai_categorization import (
    AICategorizationService,
    TaxonomyManager,
    CategorizationProvider,
    TaxonomyType,
    CategorizationStatus,
    ConfidenceLevel as CategorizationConfidenceLevel,
    MatchType,
    CategoryInfo,
    CategorySuggestion,
    CategorizationRequest,
    CategorizationResult,
    BulkCategorizationResult,
    CategoryMapping,
    CategorizationRule,
    categorize_product,
    categorize_for_channel,
    categorize_multi_taxonomy,
    bulk_categorize_products,
    map_category_to_channel,
    get_categorization_status,
    approve_categorization,
    reject_categorization,
    get_pending_categorizations,
    get_available_taxonomies,
    get_taxonomy_categories,
    search_categories,
    get_categorization_rules,
    test_categorization_connection,
)

from frappe_pim.pim.services.image_variants import (
    ImageVariantsService,
    ImageFormat,
    ResizeMode,
    BackgroundType,
    VariantStatus,
    ImageSpec,
    ChannelSpec,
    ImageVariant,
    VariantSet,
    BatchResult,
    CHANNEL_SPECS,
    generate_channel_variants,
    generate_multi_channel_variants,
    batch_generate_variants,
    get_channel_specs,
    list_available_channels,
    get_variant_specs,
    validate_image_for_channel,
    generate_product_variants,
)

from frappe_pim.pim.services.s3_storage import (
    S3StorageService,
    StorageProvider,
    ACL,
    StorageClass,
    UploadStatus,
    MediaType,
    S3Config,
    StorageLocation,
    UploadProgress,
    UploadResult,
    MediaAsset,
    BatchUploadResult,
    upload_file,
    upload_product_media,
    batch_upload_files,
    download_file,
    delete_file,
    get_signed_url,
    get_upload_url,
    list_files,
    test_s3_connection,
    get_storage_providers,
    get_storage_classes,
)

from frappe_pim.pim.services.merge_survive import (
    MergeSurviveService,
    SimilarityCalculator,
    SurvivorshipRule,
    MergeMode,
    MatchType,
    MatchStatus,
    MergeStatus,
    FieldResolution,
    MatchConfig,
    SurvivorshipConfig,
    DuplicateMatch,
    FieldMergeResult,
    MergeResult,
    DuplicateScanResult,
    find_duplicates,
    find_duplicates_for_product,
    merge_products,
    calculate_match_score,
    get_survivorship_rules,
    get_match_types,
    preview_merge,
    confirm_duplicate_match,
    get_merge_history,
    rollback_merge,
)

from frappe_pim.pim.services.print_catalog import (
    PrintCatalogService,
    CatalogConfig,
    CatalogProduct,
    CatalogResult,
    CatalogLayout,
    PageSize,
    PageOrientation,
    CatalogStatus,
    SortOrder,
    PAGE_DIMENSIONS,
    PRODUCTS_PER_PAGE,
    generate_catalog,
    generate_catalog_async,
    get_catalog_layouts,
    get_page_sizes,
    get_sort_options,
    preview_catalog,
)

from frappe_pim.pim.services.quality_scorer import (
    QualityScorer,
    QualityLevel,
    MissingField,
    DimensionScore,
    QualityScore,
    QualityReport,
    QUALITY_THRESHOLDS,
    DEFAULT_DIMENSION_WEIGHTS,
    calculate_score as calculate_quality_score,
    get_missing_fields,
    get_quality_report,
)

__all__ = [
    # GDSN Sync Classes
    "GDSNDataPoolClient",
    "GDSNSyncService",
    # GDSN Sync Functions
    "publish_to_data_pool",
    "subscribe_to_product",
    "get_sync_status",
    "process_incoming_cin",
    "process_incoming_cip",
    "sync_product_to_gdsn",
    "sync_all_products_to_gdsn",
    # Search Rank Tracker Classes
    "SearchRankTrackerService",
    "KeywordConfig",
    "RankResult",
    "RankChange",
    "TrackingResult",
    "TrendData",
    # Search Rank Tracker Enums
    "RankTrackingMethod",
    "RankChangeType",
    "RankAlertSeverity",
    # Search Rank Tracker Functions
    "track_product_rankings",
    "get_product_rank_history",
    "get_rank_trends",
    "compare_channel_rankings",
    "get_share_of_search",
    "schedule_rank_tracking",
    "scheduled_rank_tracking",
    # Price Parity Classes
    "PriceParityMonitorService",
    "PricePoint",
    "PriceComparison",
    "PriceChange",
    "PriceViolation",
    "ParityResult",
    "PriceTrend",
    "CompetitorPrice",
    # Price Parity Enums
    "ParityStatus",
    "PriceChangeType",
    "AlertSeverity",
    "PriceType",
    "ViolationType",
    # Price Parity Functions
    "monitor_product_prices",
    "get_price_parity_status",
    "get_price_history",
    "get_price_trends",
    "compare_channel_prices",
    "get_competitor_analysis",
    "check_map_violations",
    "get_price_alerts",
    "schedule_price_monitoring",
    "scheduled_price_monitoring",
    # AI Enrichment Classes
    "AIEnrichmentService",
    "EnrichmentRequest",
    "EnrichmentSuggestion",
    "EnrichmentResult",
    "BulkEnrichmentResult",
    # AI Enrichment Enums
    "AIProvider",
    "EnrichmentType",
    "EnrichmentStatus",
    "ConfidenceLevel",
    # AI Enrichment Functions
    "generate_product_description",
    "generate_seo_content",
    "generate_bullet_points",
    "extract_product_attributes",
    "suggest_product_categories",
    "enrich_product",
    "bulk_enrich_products",
    "get_enrichment_status",
    "approve_enrichment",
    "reject_enrichment",
    "get_pending_approvals",
    "get_available_enrichment_types",
    "get_ai_providers",
    # AI Translation Classes
    "AITranslationService",
    "TranslationMemoryManager",
    "GlossaryManager",
    "GlossaryTerm",
    "Glossary",
    "TranslationMemoryEntry",
    "TranslationRequest",
    "TranslationResult",
    "BulkTranslationResult",
    "ProductTranslation",
    # AI Translation Enums
    "TranslationProvider",
    "TranslationStatus",
    "TranslationQuality",
    "ContentType",
    "GlossaryMatchType",
    # AI Translation Functions
    "translate_text",
    "translate_product",
    "bulk_translate_products",
    "get_translation_memory_stats",
    "lookup_translation",
    "list_glossaries",
    "get_glossary",
    "create_glossary",
    "add_glossary_term",
    "get_supported_languages",
    "get_translation_providers",
    "approve_translation",
    "reject_translation",
    "get_pending_translations",
    "test_translation_connection",
    # AI Categorization Classes
    "AICategorizationService",
    "TaxonomyManager",
    "CategoryInfo",
    "CategorySuggestion",
    "CategorizationRequest",
    "CategorizationResult",
    "BulkCategorizationResult",
    "CategoryMapping",
    "CategorizationRule",
    # AI Categorization Enums
    "CategorizationProvider",
    "TaxonomyType",
    "CategorizationStatus",
    "CategorizationConfidenceLevel",
    "MatchType",
    # AI Categorization Functions
    "categorize_product",
    "categorize_for_channel",
    "categorize_multi_taxonomy",
    "bulk_categorize_products",
    "map_category_to_channel",
    "get_categorization_status",
    "approve_categorization",
    "reject_categorization",
    "get_pending_categorizations",
    "get_available_taxonomies",
    "get_taxonomy_categories",
    "search_categories",
    "get_categorization_rules",
    "test_categorization_connection",
    # Image Variants Classes
    "ImageVariantsService",
    "ImageSpec",
    "ChannelSpec",
    "ImageVariant",
    "VariantSet",
    "BatchResult",
    # Image Variants Enums
    "ImageFormat",
    "ResizeMode",
    "BackgroundType",
    "VariantStatus",
    # Image Variants Constants
    "CHANNEL_SPECS",
    # Image Variants Functions
    "generate_channel_variants",
    "generate_multi_channel_variants",
    "batch_generate_variants",
    "get_channel_specs",
    "list_available_channels",
    "get_variant_specs",
    "validate_image_for_channel",
    "generate_product_variants",
    # S3 Storage Classes
    "S3StorageService",
    "S3Config",
    "StorageLocation",
    "UploadProgress",
    "UploadResult",
    "MediaAsset",
    "BatchUploadResult",
    # S3 Storage Enums
    "StorageProvider",
    "ACL",
    "StorageClass",
    "UploadStatus",
    "MediaType",
    # S3 Storage Functions
    "upload_file",
    "upload_product_media",
    "batch_upload_files",
    "download_file",
    "delete_file",
    "get_signed_url",
    "get_upload_url",
    "list_files",
    "test_s3_connection",
    "get_storage_providers",
    "get_storage_classes",
    # Merge/Survive Classes
    "MergeSurviveService",
    "SimilarityCalculator",
    "MatchConfig",
    "SurvivorshipConfig",
    "DuplicateMatch",
    "FieldMergeResult",
    "MergeResult",
    "DuplicateScanResult",
    # Merge/Survive Enums
    "SurvivorshipRule",
    "MergeMode",
    "MatchType",
    "MatchStatus",
    "MergeStatus",
    "FieldResolution",
    # Merge/Survive Functions
    "find_duplicates",
    "find_duplicates_for_product",
    "merge_products",
    "calculate_match_score",
    "get_survivorship_rules",
    "get_match_types",
    "preview_merge",
    "confirm_duplicate_match",
    "get_merge_history",
    "rollback_merge",
    # Print Catalog Classes
    "PrintCatalogService",
    "CatalogConfig",
    "CatalogProduct",
    "CatalogResult",
    # Print Catalog Enums
    "CatalogLayout",
    "PageSize",
    "PageOrientation",
    "CatalogStatus",
    "SortOrder",
    # Print Catalog Constants
    "PAGE_DIMENSIONS",
    "PRODUCTS_PER_PAGE",
    # Print Catalog Functions
    "generate_catalog",
    "generate_catalog_async",
    "get_catalog_layouts",
    "get_page_sizes",
    "get_sort_options",
    "preview_catalog",
    # Quality Scorer Classes
    "QualityScorer",
    "MissingField",
    "DimensionScore",
    "QualityScore",
    "QualityReport",
    # Quality Scorer Enums
    "QualityLevel",
    # Quality Scorer Constants
    "QUALITY_THRESHOLDS",
    "DEFAULT_DIMENSION_WEIGHTS",
    # Quality Scorer Functions
    "calculate_quality_score",
    "get_missing_fields",
    "get_quality_report",
]
